## This yaml file ensures that if this job takes more than 30 seconds to run then it should terminate based on line 8 
apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: busybox
spec:
  activeDeadlineSeconds: 30
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - while true; do echo hello; sleep 10; done
        image: busybox
        name: busybox
        resources: {}
      restartPolicy: Never
status: {}


#Implement canary deployment by running two instances of nginx marked as version=v1 #
# and version=v2 so that the load is balanced at 75%-25% ratio




##create secret and decode it
kubectl get secret mysecret2 -o yaml
echo -n YWRtaW4= | base64 -d # on MAC it is -D, which decodes the value and shows 'admin'

